#' Convert a dataframe to a vcf
#'
#' @family utils
#' @importFrom echoconda find_packages
#' @examples
#' data("merge_DT")
#'
dataframe_2_vcf <- function(dat,
                            samplename="GWAS",
                            reference_fasta="/pd-omics/tools/polyfun/reference_fasta/hg19.fa.gz",
                            output_vcf="./GWAS_converted.vcf",
                            conda_env="echoR"){
  # See: http://www.htslib.org/doc/1.2/bcftools.html
  # TSV conversion:
  #   --tsv2vcf file
  # convert from TSV (tab-separated values) format (such as generated by 23andMe) to VCF. The input file fields can be tab- or space- delimited
  # -c, --columns list
  # comma-separated list of fields in the input file. In the current version, the fields CHROM, POS, ID, and AA are expected and can appear in arbitrary order, columns which should be ignored in the input file can be indicated by "-". The AA field lists alleles on the forward reference strand, for example "CC" or "CT" for diploid genotypes or "C" for haploid genotypes (sex chromosomes). Insertions and deletions are not supported yet, missing data can be indicated with "--".
  # -f, --fasta-ref file
  # reference sequence in fasta format
  # -s, --samples LIST
  # list of sample names. See Common Options
  # -S, --samples-file FILE
  # file of sample names. See Common Options

  # STEP 1
  ## Save df as tsv w/ ID,CHROM,POS,AA
  dat_mod <- dat %>%
    dplyr::mutate(AA = paste0(A1,A2), CHROM=paste0("chr",CHR)) %>%
    dplyr::select(ID=SNP, CHROM, POS, AA)
  data.table::fwrite(x = dat_mod, file="./tmp.tsv",sep = "\t")

  # STEP 2
  bcftools <- echoconda::find_packages(package = "bcftools",
                                 conda_env = conda_env)
  ## Convert tsv to vcf with bcftools
  cmd <- paste(bcftools,
               "convert",
               "-c ID,CHROM,POS,AA",
               "-s", samplename,
               "-f",reference_fasta,
               "--tsv2vcf tmp.tsv",
               " -Oz", # options
               "-o",output_vcf)
  print(cmd)
  system(cmd)
  # Remove tmps
  out <- file.remove("./tmp.tsv")
  return(output_vcf)
}

